# Generated by Django 6.0.5 on 2026-06-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ismailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentStreak',
            field=models.IntegerField(default=0),
        ),
    ]
