# Generated by Django 6.0.5 on 2026-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budgetWarning',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='fiscalYearStart',
            field=models.CharField(default='Januar', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='Deutsch', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='numberFormat',
            field=models.CharField(default='Punkt', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='popupsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacyMode',
            field=models.BooleanField(default=False),
        ),
    ]
