# Generated by Django 6.0.6 on 2026-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_ID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
