# Generated by Django 6.0.5 on 2026-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyCurrency',
            field=models.CharField(default='EUR', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='companyLegalForm',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='companyLocation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
