# Generated by Django 6.0.5 on 2026-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_companycurrency_company_companylegalform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyCapital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='companyGoal',
            field=models.IntegerField(default=0),
        ),
    ]
