# Generated by Django 6.0.5 on 2026-06-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_companycapital_company_companygoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyOwner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
